-- ============================================================================
-- Policy facts, seeded from the website (contract v1.4).
--
-- Generated from rising-star-web-spark/docs/LEGAL_FACT_KEYS.json (2026-10-05,
-- 47 keys) plus research guidance for each fact: what it means, what to
-- check and where. Every current value becomes a version so the live site does
-- not change when this is deployed:
--
--   owner_confirmed            → published, verified (review due in 12 months)
--   default_needs_verification → published but flagged "verify" (review due now)
--   needs_value                → needs_research, not published (the site keeps
--                                its bundled placeholder)
--
-- Technical keys (editable = false) are set in the website's code; they are
-- listed for reference and never reach public.site_legal_facts.
-- Document baselines match the website's bundled DOCUMENTS versions.
-- ============================================================================

SET search_path = ops, public, extensions;

INSERT INTO ops.legal_facts (key, label, category, help, links, editable, documents, preview, sort_order) VALUES
  ($q$brandName$q$, $q$Brand name (d/b/a)$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'terms', 'registration_terms']::text[], $q$…doing business as {value} (“Rising Stars”, “we”, “us”).$q$, 500),
  ($q$legalEntityName$q$, $q$Legal entity name$q$, $q$Business$q$, $q$The exact name of the company as registered with the Texas Secretary of State — the party families and the website contract with. Search SOSDirect (a small fee per search) or the Comptroller's free franchise-tax lookup; copy the name exactly, including “LLC”. It must match the certificate of formation and the bank account.$q$, $q$[{"label":"Texas SOS — SOSDirect (business entity search)","url":"https://www.sos.state.tx.us/corp/sosda/index.shtml"},{"label":"Texas Comptroller — franchise tax account status","url":"https://comptroller.texas.gov/taxes/franchise/account-status/search"}]$q$::jsonb, true, ARRAY['privacy', 'terms', 'registration_terms']::text[], $q$These Terms of Use are an agreement between you and {value}, doing business as Rising Stars Youth Academy.$q$, 1),
  ($q$entityType$q$, $q$Entity type$q$, $q$Business$q$, $q$What kind of entity the business is (e.g. limited liability company) and, if useful, the state it was formed in. Shown on the SOS record next to the name (“Domestic Limited Liability Company (LLC)”).$q$, $q$[{"label":"Texas SOS — SOSDirect (business entity search)","url":"https://www.sos.state.tx.us/corp/sosda/index.shtml"}]$q$::jsonb, true, '{}'::text[], $q$Rising Stars LLC is a Texas {value}.$q$, 2),
  ($q$mailingAddress$q$, $q$Mailing address for legal notices$q$, $q$Business$q$, $q$A full postal address where letters, legal notices and privacy requests reach the business: street number, street, city, state, ZIP. CAN-SPAM requires a valid physical postal address in every marketing email (a registered PO box or private mailbox counts). Check it against the SOS registered-office record and the USPS ZIP lookup. The street number is still missing.$q$, $q$[{"label":"USPS ZIP Code lookup (verify the address)","url":"https://tools.usps.com/zip-code-lookup.htm"},{"label":"FTC — CAN-SPAM compliance guide (postal address rule)","url":"https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business"},{"label":"Texas SOS — SOSDirect (business entity search)","url":"https://www.sos.state.tx.us/corp/sosda/index.shtml"}]$q$::jsonb, true, ARRAY['privacy', 'terms']::text[], $q$Mail: Rising Stars LLC, {value}.$q$, 3),
  ($q$serviceArea$q$, $q$Service area$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy']::text[], $q$…coach-led sports programs for children ages 4–12 in {value}.$q$, 504),
  ($q$phoneDisplay$q$, $q$Phone number (as shown)$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'terms', 'registration_terms', 'child_safety', 'accessibility', 'privacy_choices']::text[], $q$Call or text {value}.$q$, 505),
  ($q$phoneE164$q$, $q$Phone number (dialable)$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'terms', 'registration_terms', 'child_safety', 'accessibility', 'privacy_choices']::text[], $q$tel:{value}$q$, 506),
  ($q$email$q$, $q$Contact email$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['terms', 'registration_terms', 'child_safety', 'accessibility']::text[], $q$Questions: {value}$q$, 507),
  ($q$privacyEmail$q$, $q$Privacy contact email$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'privacy_choices']::text[], $q$You can also email {value}.$q$, 508),
  ($q$schoolApprovals$q$, $q$School approvals$q$, $q$Business$q$, $q$A sentence saying the host schools approve the programs. Only keep it if every current host district or charter school has actually approved the program (a facility-use agreement, MOU or principal's written approval). Keep a copy of each approval; check the Schools page for the current list.$q$, $q$[{"label":"Texas Education Agency — school district directory (AskTED)","url":"https://tea4avholly.tea.state.tx.us/TEA.AskTED.Web/Forms/Home.aspx"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q${value} On school grounds we also follow each host school’s visitor and safety rules.$q$, 9),
  ($q$safeguardingContact$q$, $q$Child Safety Officer$q$, $q$Business$q$, $q$The named person (or title) who receives safeguarding concerns from parents and coaches. They must be reachable, trained in mandatory reporting, and know the Texas Abuse Hotline process. Use a name and role the public can recognise; don't include a personal phone number.$q$, $q$[{"label":"Tex. Fam. Code ch. 261 (duty to report abuse)","url":"https://statutes.capitol.texas.gov/Docs/FA/htm/FA.261.htm"},{"label":"Texas DFPS — training for professionals who must report","url":"https://www.dfps.texas.gov/Training/Reporting/"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q$Our designated child-safety officer is {value}. They receive concerns, …$q$, 10),
  ($q$instagramUrl$q$, $q$Instagram link$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, '{}'::text[], $q${value}$q$, 511),
  ($q$instagramHandle$q$, $q$Instagram handle$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, '{}'::text[], $q${value}$q$, 512),
  ($q$siteUrl$q$, $q$Website address$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy']::text[], $q$This policy covers this website ({value}), …$q$, 513),
  ($q$coachOsUrl$q$, $q$CoachOS address$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy']::text[], $q$…our back-office system (CoachOS, at {value}), …$q$, 514),
  ($q$governingLaw$q$, $q$Governing law$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['terms', 'registration_terms']::text[], $q$This Agreement is governed by the laws of {value}.$q$, 515),
  ($q$venue$q$, $q$Venue for disputes (counties)$q$, $q$Business$q$, $q$Which Texas county's courts hear a dispute. It should list every county where programs actually run — check the Schools and Programs pages (Irving and most of Dallas are Dallas County; Fort Worth is Tarrant; Plano/Frisco are Collin; Denton/Lewisville are Denton). Have the attorney confirm the wording at the annual review.$q$, $q$[{"label":"Tex. Civ. Prac. & Rem. Code ch. 15 (venue)","url":"https://statutes.capitol.texas.gov/Docs/CP/htm/CP.15.htm"}]$q$::jsonb, true, ARRAY['terms', 'registration_terms']::text[], $q$Any lawsuit must be brought in the state or federal courts located in {value}.$q$, 16),
  ($q$ageRange$q$, $q$Age range$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'registration_terms']::text[], $q$Programs are for children ages {value}, grouped as each program describes.$q$, 517),
  ($q$paymentProcessor$q$, $q$Payment processor$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, ARRAY['privacy', 'registration_terms']::text[], $q$…processed by {value}. We do not see or store your full card number.$q$, 518),
  ($q$billingCycle$q$, $q$Billing cycle$q$, $q$Money$q$, $q$When and how families are invoiced. Must match what CoachOS actually does: check Settings (invoice day, autopay) and a recent invoice on the Payments page.$q$, $q$[{"label":"Stripe — invoicing basics","url":"https://docs.stripe.com/invoicing"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$Payments are made through our CoachOS family portal and processed by Stripe. {value}$q$, 119),
  ($q$refundWindow$q$, $q$Refund policy$q$, $q$Money$q$, $q$The refund rule families agree to. The owner chose “all sales final, exceptions at our discretion”. Texas DTPA forbids misrepresenting refund rights, so the page must match practice; programs Rising Stars cancels are still refunded or credited. Confirm with the attorney at the annual review.$q$, $q$[{"label":"Texas DTPA (Tex. Bus. & Com. Code ch. 17)","url":"https://statutes.capitol.texas.gov/Docs/BC/htm/BC.17.htm"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$All sales are final: {value}$q$, 120),
  ($q$cancellationNotice$q$, $q$Cancellation notice$q$, $q$Money$q$, $q$How a family stops future monthly charges and by when. Must match how billing works (invoices generated on the 1st). If a family cancels by text or WhatsApp, record it the same day so the next invoice isn't generated.$q$, $q$[{"label":"FTC — negative option / easy cancellation guidance","url":"https://www.ftc.gov/legal-library/browse/rules/negative-option-rule"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$Stopping monthly billing: {value}$q$, 121),
  ($q$makeUpPolicy$q$, $q$Sessions we cancel (make-ups)$q$, $q$Money$q$, $q$What families get when Rising Stars cancels a session (weather, venue, coach unavailable). Should be something you can always honour — a make-up or a credit — to stay clear of the DTPA.$q$, $q$[{"label":"Texas DTPA (Tex. Bus. & Com. Code ch. 17)","url":"https://statutes.capitol.texas.gov/Docs/BC/htm/BC.17.htm"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$Sessions we cancel (weather, venue or coach unavailability): {value}$q$, 122),
  ($q$missedSessionPolicy$q$, $q$Sessions a family misses$q$, $q$Money$q$, $q$What happens when a child misses a session the program ran. Confirm it matches what coaches actually tell parents.$q$, $q$[]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$Sessions your child misses: {value}$q$, 123),
  ($q$lateFee$q$, $q$Late payment fee$q$, $q$Money$q$, $q$Whether a late fee is charged and what happens when an invoice is overdue. If you ever add a fee, it must be stated here first and be reasonable; check the overdue rules in Settings match the number of days written here.$q$, $q$[]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$If a payment fails, we will let you know and may pause participation until it is resolved. Late fee: {value}$q$, 124),
  ($q$latePickupPolicy$q$, $q$Late pick-up$q$, $q$Money$q$, $q$What coaches do when a parent is late. Ask the coaches whether this is what they actually do (how many minutes before calling, who stays with the child).$q$, $q$[]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$…and keep trying to reach you and your emergency contacts. {value}$q$, 125),
  ($q$heatPolicy$q$, $q$Heat & lightning policy$q$, $q$Day to day$q$, $q$The heat-index thresholds coaches follow outdoors and what happens with lightning. Check the coaches really check the heat index (NWS / a weather app) before each outdoor session. The UIL heat guidance and the NWS 30-30 lightning rule are good references.$q$, $q$[{"label":"NWS — heat index chart","url":"https://www.weather.gov/safety/heat-index"},{"label":"UIL — heat stress and athletic participation","url":"https://www.uiltexas.org/health/info/heat-stress-and-athletic-participation"},{"label":"NWS — lightning safety","url":"https://www.weather.gov/safety/lightning"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$…or stop activity as conditions require: {value}. Please send your child with a water bottle…$q$, 226),
  ($q$youthCampLicense$q$, $q$Youth camp license status$q$, $q$Safety & licensing$q$, $q$Whether Rising Stars holds a DSHS youth camp license. A program with 5+ children for 4+ consecutive days is a youth camp under Tex. Health & Safety Code ch. 141 and needs a license first. Confirm no program on the schedule meets 4 or more days in a row (CoachOS warns about these).$q$, $q$[{"label":"DSHS — Youth Camp Program","url":"https://www.dshs.texas.gov/youth-camp-program"},{"label":"Tex. Health & Safety Code ch. 141","url":"https://statutes.capitol.texas.gov/Docs/HS/htm/HS.141.htm"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q$Our status: {value}$q$, 327),
  ($q$insurance$q$, $q$Insurance statement$q$, $q$Business$q$, $q$A public sentence saying the business is insured. Check the current certificate of insurance: that general liability (and participant accident, if any) is in force for this season. Don't put the carrier, policy number or limits here — record those privately on the Checklist tab (Insurance renewal).$q$, $q$[{"label":"Texas Department of Insurance — business insurance help","url":"https://www.tdi.texas.gov/"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$Insurance: {value}$q$, 28),
  ($q$backgroundCheckProvider$q$, $q$Background checks$q$, $q$Safety & licensing$q$, $q$Which background check every coach passes and how often it is renewed. Check each coach's record on the Coaches page. At minimum: Texas DPS criminal history and the DPS and national (NSOPW) sex-offender registries; a vendor check must follow FCRA rules (written consent, adverse-action notices).$q$, $q$[{"label":"Texas DPS — criminal history (conviction) search","url":"https://publicsite.dps.texas.gov/ConvictionNameSearch/"},{"label":"Texas DPS — sex offender registry","url":"https://publicsite.dps.texas.gov/SexOffenderRegistry"},{"label":"NSOPW — national sex offender search","url":"https://www.nsopw.gov/"},{"label":"FTC — background checks: what employers need to know","url":"https://www.ftc.gov/business-guidance/resources/background-checks-what-employers-need-know"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q$…run a criminal background check through {value};$q$, 329),
  ($q$safeguardingTraining$q$, $q$Abuse-prevention training$q$, $q$Safety & licensing$q$, $q$The abuse-prevention and mandatory-reporting course every coach completes and how often. Check each coach's certificate date on the Coaches page. If a youth camp is ever run, DSHS requires an approved sexual-abuse training (§141.0095).$q$, $q$[{"label":"Darkness to Light — Stewards of Children","url":"https://www.d2l.org/education/stewards-of-children/"},{"label":"U.S. Center for SafeSport — training","url":"https://uscenterforsafesport.org/training-and-education/"},{"label":"Texas DFPS — report abuse / reporting duties","url":"https://www.txabusehotline.org/"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q$abuse-prevention training on recognizing, preventing and reporting abuse and grooming: {value};$q$, 330),
  ($q$firstAidCertification$q$, $q$CPR, AED & first aid$q$, $q$Safety & licensing$q$, $q$What CPR/AED/first-aid certification coaches hold. Only say “every coach” if it is true today: check the expiry date on each coach's card (Red Cross and AHA cards last 2 years) on the Coaches page.$q$, $q$[{"label":"American Red Cross — CPR/AED/first aid classes & certificate lookup","url":"https://www.redcross.org/take-a-class"},{"label":"American Heart Association — CPR & first aid","url":"https://cpr.heart.org/"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$…coaching. {value}$q$, 331),
  ($q$ngbAffiliation$q$, $q$National governing body (SafeSport)$q$, $q$Safety & licensing$q$, $q$Whether Rising Stars belongs to a national governing body (US Soccer, USA Basketball, …) or takes part in interstate/international competition — which would bring the federal SafeSport Act's reporting and training duties. Re-check whenever a team joins a league or travels out of state.$q$, $q$[{"label":"U.S. Center for SafeSport — who is covered","url":"https://uscenterforsafesport.org/"},{"label":"36 U.S.C. §220541 (SafeSport duties)","url":"https://www.law.cornell.edu/uscode/text/36/220541"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q$Our status: {value}. Whether or not it applies, …$q$, 332),
  ($q$medicationPolicy$q$, $q$Medication$q$, $q$Day to day$q$, $q$What staff will and won't do with medication. Confirm with coaches; if any coach is trained to use an epinephrine auto-injector, record the training. Texas lets students self-carry asthma and anaphylaxis medicine at school (Educ. Code §38.015, §38.0151 — schools only, a useful benchmark).$q$, $q$[{"label":"Tex. Educ. Code ch. 38 (§38.015, §38.0151)","url":"https://statutes.capitol.texas.gov/Docs/ED/htm/ED.38.htm"},{"label":"FARE — food allergy & anaphylaxis emergency care plans","url":"https://www.foodallergy.org/"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q${value}$q$, 233),
  ($q$aedAvailability$q$, $q$AED availability$q$, $q$Day to day$q$, $q$Where the nearest AED is during sessions. Texas public school campuses must have an AED available (Tex. Educ. Code §38.017). For each non-school venue, confirm with the venue where its AED is; if there is none, keep this sentence honest.$q$, $q$[{"label":"Tex. Educ. Code §38.017 (AEDs at schools)","url":"https://statutes.capitol.texas.gov/Docs/ED/htm/ED.38.htm#38.017"},{"label":"Tex. Health & Safety Code ch. 779 (AEDs)","url":"https://statutes.capitol.texas.gov/Docs/HS/htm/HS.779.htm"}]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q${value}$q$, 234),
  ($q$conductRefund$q$, $q$Refund after removal for conduct$q$, $q$Money$q$, $q$Whether any money is returned when a child or family is removed for conduct. Should agree with the refund policy above.$q$, $q$[]$q$::jsonb, true, ARRAY['registration_terms']::text[], $q$…participant’s or family’s participation. {value}$q$, 135),
  ($q$photoDeviceStorage$q$, $q$Where photos are kept$q$, $q$Day to day$q$, $q$Where photos of children are taken and stored. Check how coaches actually take photos; if personal phones are used, the photos must be uploaded the same day and deleted. Only children with a photo release may appear on the website (CoachOS checks this).$q$, $q$[{"label":"FTC — COPPA FAQ (photos of children are personal information)","url":"https://www.ftc.gov/business-guidance/resources/complying-coppa-frequently-asked-questions"}]$q$::jsonb, true, ARRAY['child_safety']::text[], $q${value}$q$, 236),
  ($q$gaMeasurementId$q$, $q$Google Analytics ID$q$, $q$Technical (not editable)$q$, $q$Set in the website's code (src/config/legal.ts), not here: if it is wrong, ask the website engineer to change it. Shown for reference so the whole fact sheet is in one place.$q$, $q$[]$q$::jsonb, false, '{}'::text[], $q${value}$q$, 537),
  ($q$smsProvider$q$, $q$Who sends text messages$q$, $q$Day to day$q$, $q$Who sends texts to parents. Today staff text by hand from the business phone. If a texting platform (Twilio, SimpleTexting, etc.) is ever used, name it here before the first message — it then receives parents' numbers.$q$, $q$[{"label":"FCC — TCPA consumer guide","url":"https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q${value} — sends text messages.$q$, 238),
  ($q$retention.registration$q$, $q$Keep: registration & attendance records$q$, $q$Retention$q$, $q$How long registration, roster and attendance records are kept. COPPA requires a written retention policy and deletion when no longer needed. Should agree with what CoachOS actually keeps (Audit & Compliance → Data kept) and with the incident-report period.$q$, $q$[{"label":"COPPA rule — 16 CFR 312.10 (retention)","url":"https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312/section-312.10"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Registration, roster and attendance records — {value}$q$, 439),
  ($q$retention.medical$q$, $q$Keep: children's health notes$q$, $q$Retention$q$, $q$How long a child's medical/allergy note is kept. CoachOS's nightly clean-up removes it 12 months after the last active enrollment (Data kept tab) — this must say the same, or the code must change.$q$, $q$[{"label":"COPPA rule — 16 CFR 312.10 (retention)","url":"https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312/section-312.10"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Children’s health notes — {value}$q$, 440),
  ($q$retention.incidentReports$q$, $q$Keep: incident & safeguarding reports$q$, $q$Retention$q$, $q$How long injury and safeguarding reports are kept. Texas's 2-year limitations period for injury claims doesn't start until the child turns 18 (tolling), so keep them until at least 20; ask the attorney and the insurer, who may want longer.$q$, $q$[{"label":"Tex. Civ. Prac. & Rem. Code ch. 16 (§16.001 minors, §16.003 two years)","url":"https://statutes.capitol.texas.gov/Docs/CP/htm/CP.16.htm"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Injury and incident reports, safeguarding records — {value}$q$, 441),
  ($q$retention.payments$q$, $q$Keep: payment & accounting records$q$, $q$Retention$q$, $q$How long payment and accounting records are kept. The IRS asks for 3–7 years depending on the record; the Texas Comptroller can audit 4 years back. Ask the bookkeeper/CPA.$q$, $q$[{"label":"IRS — how long should I keep records?","url":"https://www.irs.gov/businesses/small-businesses-self-employed/how-long-should-i-keep-records"},{"label":"Texas Comptroller — records retention for audits","url":"https://comptroller.texas.gov/taxes/audit/"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Payment and accounting records — {value}$q$, 442),
  ($q$retention.inquiries$q$, $q$Keep: website inquiries & leads$q$, $q$Retention$q$, $q$How long contact-form inquiries and leads are kept. CoachOS removes the contact details after 24 months (Data kept tab) — keep the two in step.$q$, $q$[]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Contact-form inquiries and leads — {value}$q$, 443),
  ($q$retention.privacyRequests$q$, $q$Keep: privacy requests$q$, $q$Retention$q$, $q$How long the record of a privacy request (and our answer) is kept. CoachOS removes the requester's contact details 36 months after the request closes and keeps the record (Data kept tab).$q$, $q$[{"label":"Texas Data Privacy and Security Act (ch. 541)","url":"https://statutes.capitol.texas.gov/Docs/BC/htm/BC.541.htm"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Privacy requests — {value}$q$, 444),
  ($q$retention.analytics$q$, $q$Keep: Google Analytics data$q$, $q$Retention$q$, $q$How long Google Analytics keeps event data. Check in GA4: Admin → Data collection and modification → Data retention (should be 14 months), and that Google signals are off. The Checklist tab has a recurring check.$q$, $q$[{"label":"Google — GA4 data retention","url":"https://support.google.com/analytics/answer/7667196"},{"label":"Google — Google signals","url":"https://support.google.com/analytics/answer/9445345"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Google Analytics data — {value}$q$, 445),
  ($q$retention.errorLogs$q$, $q$Keep: error logs (Sentry)$q$, $q$Retention$q$, $q$How long error reports are kept by Sentry. Retention depends on the Sentry plan (90 days on the standard plans); check the organisation's settings and that data scrubbing stays on.$q$, $q$[{"label":"Sentry — data retention by plan","url":"https://sentry.io/pricing/"},{"label":"Sentry — scrubbing sensitive data","url":"https://docs.sentry.io/security-legal-pii/scrubbing/"}]$q$::jsonb, true, ARRAY['privacy']::text[], $q$Error diagnostics (Sentry) — {value}$q$, 446)
ON CONFLICT (key) DO NOTHING;

INSERT INTO ops.legal_fact_versions (key, value, status, verified, research_notes, published_at, reviewed_by, review_due, edited_by)
SELECT v.key, v.value, v.status, v.verified, v.notes, v.published_at, v.reviewed_by, v.review_due, 'system:seed'
  FROM (VALUES
  ($q$brandName$q$, $q$Rising Stars Youth Academy$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$legalEntityName$q$, $q$Rising Stars LLC$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$entityType$q$, $q$limited liability company$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$mailingAddress$q$, $q$[CONFIRM: street number] Comal Dr, Irving, TX 75039$q$, 'needs_research', false, $q$Seeded from the website (2026-10-05) with a placeholder: the value is still missing. Research it and send it for review.$q$, NULL, NULL, NULL),
  ($q$serviceArea$q$, $q$Dallas–Fort Worth, Texas$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$phoneDisplay$q$, $q$972-900-0292$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$phoneE164$q$, $q$+1-972-900-0292$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$email$q$, $q$RisingStarsDFW@gmail.com$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$privacyEmail$q$, $q$RisingStarsDFW@gmail.com$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$schoolApprovals$q$, $q$Our programs are approved by the Texas school districts and charter schools that host them.$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$safeguardingContact$q$, $q$Officer Jones, our Child Safety Officer$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$instagramUrl$q$, $q$https://www.instagram.com/risingstars.dfw/$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$instagramHandle$q$, $q$@risingstars.dfw$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$siteUrl$q$, $q$https://risingstars.training$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$coachOsUrl$q$, $q$https://app.risingstars.training$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$governingLaw$q$, $q$the State of Texas$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$venue$q$, $q$the county in Texas where the program took place (Dallas, Tarrant, Collin or Denton County)$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$ageRange$q$, $q$4–12$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$paymentProcessor$q$, $q$Stripe$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$billingCycle$q$, $q$We invoice monthly through CoachOS at the start of each month your child is enrolled.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$refundWindow$q$, $q$All payments are final and non-refundable. In special circumstances (for example a serious injury or illness that keeps your child from taking part, or a family relocation) you may ask for an exception; any refund or credit is at Rising Stars’ discretion.$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$cancellationNotice$q$, $q$Tell us before the 1st of the next month to stop future monthly charges. The current month is not refunded.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$makeUpPolicy$q$, $q$We offer a make-up session; if a make-up isn’t possible, we give a credit toward a future month.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$missedSessionPolicy$q$, $q$They are not refunded, credited or made up.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$lateFee$q$, $q$none. If an invoice is more than 14 days overdue, your child’s spot may be released to the waitlist.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$latePickupPolicy$q$, $q$Please pick up on time. A coach always stays with your child. After 15 minutes we call you and then your emergency contacts; repeated late pick-ups may lead to removal from the program. There is no late pick-up fee.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$heatPolicy$q$, $q$We check the heat index before every outdoor session. At 90°F or above we add water and shade breaks at least every 15 minutes; at 100°F or above we shorten the session and lower its intensity; at 105°F or above, or during lightning, we move indoors or cancel$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$youthCampLicense$q$, $q$We do not hold a youth camp license and do not run youth camps. Our programs meet fewer than four consecutive days, so they are not youth camps under ch. 141. Before we ever offer a program that meets four or more consecutive days, we will obtain a DSHS youth camp license first.$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$insurance$q$, $q$Rising Stars Youth Academy is insured. Details of our coverage are available to host schools and families on request.$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$backgroundCheckProvider$q$, $q$the screening required by each host school district or charter school, plus a national criminal background check renewed every 2 years$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$safeguardingTraining$q$, $q$an abuse-prevention and mandatory-reporting course (such as Darkness to Light’s Stewards of Children) completed before working with children and renewed every 2 years$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$firstAidCertification$q$, $q$Every coach holds current CPR, AED and first aid certification from the American Red Cross or the American Heart Association.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$ngbAffiliation$q$, $q$Rising Stars is not a member of any national governing body and does not take part in interstate or international competition, so the Act does not apply to us$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$medicationPolicy$q$, $q$Staff do not give routine medication. Children may carry and use their own asthma inhalers and epinephrine auto-injectors, and staff trained to do so may help in an emergency. Tell us about these in the registration form.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$aedAvailability$q$, $q$Texas public school campuses must keep an AED on site (Tex. Educ. Code §38.017); coaches learn where it is before the first session. At other venues coaches identify the nearest AED in advance and call 911 first in any emergency.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$conductRefund$q$, $q$No refund or credit is given, consistent with our no-refund policy.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$photoDeviceStorage$q$, $q$Photos are taken on Rising Stars devices or uploaded to the CoachOS photo library the same day and deleted from personal phones.$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$gaMeasurementId$q$, $q$G-38R9243PKK$q$, 'published', false, $q$Managed in the website's code.$q$, now(), 'system:seed', NULL),
  ($q$smsProvider$q$, $q$Rising Stars staff (sent directly from our business phone; we do not use a third-party texting service)$q$, 'published', true, $q$Seeded from the website's bundled value (src/config/legal.ts, docs/LEGAL_FACT_KEYS.json, 2026-10-05). Confirmed by the owner on 2026-10-05.$q$, now(), 'system:seed', (current_date + interval '12 months')::date),
  ($q$retention.registration$q$, $q$while your child is enrolled and 3 years after the last program they attended$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.medical$q$, $q$deleted 12 months after the child’s last active enrollment, unless an incident report requires longer$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.incidentReports$q$, $q$until the child turns 21 (Texas’ two-year limitations period runs from age 18, plus one year of margin)$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.payments$q$, $q$7 years, for tax and accounting records (names and contact details are removed if you ask us to delete your data)$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.inquiries$q$, $q$24 months after we receive them$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.privacyRequests$q$, $q$36 months after the request is closed (the record of the request and our response)$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.analytics$q$, $q$14 months (Google Analytics data retention setting)$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date),
  ($q$retention.errorLogs$q$, $q$up to 90 days (Sentry), with personal details removed before they are sent$q$, 'published', false, $q$Seeded from the website's bundled value (src/config/legal.ts, 2026-10-05). A default chosen by the website team, not yet checked: research it, correct it if needed, and send it for review.$q$, now(), 'system:seed', current_date)
  ) AS v(key, value, status, verified, notes, published_at, reviewed_by, review_due)
 WHERE NOT EXISTS (SELECT 1 FROM ops.legal_fact_versions x WHERE x.key = v.key);

INSERT INTO ops.legal_document_versions (document, version, effective_date, fact_keys, published_by)
SELECT d, '2026-10-05', DATE '2026-10-05', '{}', 'system:seed'
  FROM unnest(ARRAY['privacy', 'terms', 'registration_terms', 'child_safety', 'accessibility', 'privacy_choices']) AS d
ON CONFLICT (document, version) DO NOTHING;
